autocomplete: autocomplete.c
	gcc -Wall -Werror -std=c11 -o autocomplete autocomplete.c

autocompleteDebug: autocomplete.c
	gcc -Wall -Werror -std=c11 -g -o autocompleteDebug autocomplete.c

clean: 
	rm -f autocomplete
	rm -f autocompleteDebug
